language: node_js

# TODO: enable when windows is faster on travis, currently causes "No output has been received in the last 10m0s"
# cache: npm
cache: false

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - check
  - test
  - tag

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4

script: npx nyc -s npx aegir test -t node --timeout 10000 --bail
after_success:
  - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir build --bundlesize
        - npx aegir dep-check -- -i wrtc -i electron-webrtc
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npx aegir test -t browser -t webworker -- --browsers FirefoxHeadless

    - stage: test
      name: electron-main
      os: osx
      script:
        - npx aegir test -t electron-main --bail --timeout 10000

    - stage: test
      name: electron-renderer
      os: osx
      script:
        - npx aegir test -t electron-renderer --bail --timeout 10000

    - stage: test
      name: interop node
      script:
        - cd node_modules/ipfs-interop
        - IPFS_JS_EXEC=./../../src/cli/bin.js IPFS_REUSEPORT=false npx aegir test -t node --bail

    - stage: test
      name: interop browser
      script:
        - cd node_modules/ipfs-interop
        - IPFS_JS_EXEC=./../../src/cli/bin.js IPFS_REUSEPORT=false npx aegir test -t browser --bail

    - stage: test
      name: interop electron-main
      os: osx
      script:
        - cd node_modules/ipfs-interop
        - IPFS_JS_EXEC=./../../src/cli/bin.js IPFS_REUSEPORT=false npx aegir test -t electron-main -f ./test/node.js --bail --timeout 10000

    - stage: test
      name: interop electron-renderer
      os: osx
      script:
        - cd node_modules/ipfs-interop
        - IPFS_JS_EXEC=./../../src/cli/bin.js IPFS_REUSEPORT=false npx aegir test -t electron-renderer -f ./test/browser.js --bail --timeout 10000

    - stage: test
      if: branch =~ /^release\/.*$/
      name: ipfs-companion
      script:
        - npm run test:external -- ipfs-companion https://github.com/ipfs-shipyard/ipfs-companion.git

    - stage: test
      if: branch =~ /^release\/.*$/
      name: npm-on-ipfs
      script:
        - npm run test:external -- npm-on-ipfs https://github.com/ipfs-shipyard/npm-on-ipfs.git

    - stage: test
      if: branch =~ /^release\/.*$/
      name: ipfs-pubsub-room
      script:
        - npm run test:external -- ipfs-pubsub-room https://github.com/ipfs-shipyard/ipfs-pubsub-room.git --branch upgrade-to-latest-js-ipfs-rc

    - stage: test
      if: branch =~ /^release\/.*$/
      name: peer-base
      script:
        - npm run test:external -- peer-base https://github.com/achingbrain/peer-base.git --branch upgrade-to-latest-ipfs-rc

    - stage: test
      if: branch =~ /^release\/.*$/
      name: external - service-worker-gateway
      script:
        - npm run test:external -- service-worker-gateway https://github.com/ipfs-shipyard/service-worker-gateway.git

    - stage: test
      if: branch =~ /^release\/.*$/
      name: external - orbit-db
      script:
        - npm run test:external -- orbit-db https://github.com/orbitdb/orbit-db.git

    - stage: test
      if: branch =~ /^release\/.*$/
      name: external - ipfs-log
      script:
        - npm run test:external -- ipfs-log https://github.com/orbitdb/ipfs-log.git

    - stage: test
      if: branch =~ /^release\/.*$/
      name: external - sidetree
      script:
        - npm run test:external -- sidetree https://github.com/decentralized-identity/sidetree.git

    - stage: tag
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: update-last-successful-build
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git remote set-url origin https://$TRAVIS_GITHUB_USER:$TRAVIS_GITHUB_TOKEN@github.com/ipfs/js-ipfs.git
        - npx aegir update-last-successful-build

notifications:
  email: false
