language: node_js
dist: bionic

services:
  - xvfb

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - test
  - release-rc
  - release-docker
  - test-external

node_js:
  - 'lts/*'
  - 'node'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # These are required to run webkit
    - libwoff1
    - libopus0
    - libwebp6
    - libwebpdemux2
    - libenchant1c2a
    - libgudev-1.0-0
    - libsecret-1-0
    - libhyphen0
    - libgdk-pixbuf2.0-0
    - libegl1
    - libgles2
    - libevent-2.1-6
    - libnotify4
    - libxslt1.1
    - libvpx5
    # gstreamer and plugins to support video playback in WebKit.
    - gstreamer1.0-gl
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    # This is required to run chromium
    - libgbm1

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi
  # only run jobs in packages that have changed since master in PR builds
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export RUN_SINCE='--since master' ; fi
  # modules with pre-built binaries may not have deployed versions for bleeding-edge node so this lets us fall back to building from source
  - npm install -g node-pre-gyp

script:
  - npm run test:node -- $RUN_SINCE -- -- --timeout 10000 --bail

jobs:
  allow_failures:
    - name: external - ipfs-webui
    - name: external - ipfs-companion
    - name: external - npm-on-ipfs
    - name: external - peer-base
    - name: external - service-worker-gateway
    - name: external - orbit-db
    - name: external - ipfs-log
    - name: external - sidetree

  include:
    - stage: test
      name: lint
      script:
        - npm run lint -- $RUN_SINCE --concurrency 1

    - stage: test
      name: dep-check (production deps)
      script:
        - npm run dep-check -- $RUN_SINCE -- -- -p

    - stage: test
      name: dep-check (unused deps)
      script:
        - npm run dep-check -- $RUN_SINCE -- -- -- --unused

    - stage: test
      name: chrome
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail

    - stage: test
      name: chrome webworker
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail --timeout 60000

    - stage: test
      name: firefox
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail -- --browser firefox

    - stage: test
      name: firefox webworker
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail --timeout 60000 -- --browser firefox

    - stage: test
      name: webkit
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail -- --browser webkit

    - stage: test
      name: webkit webworker
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail --timeout 60000 -- --browser webkit

    - stage: test
      name: electron-main
      script:
        - npm run test:electron-main -- $RUN_SINCE -- -- --bail --timeout 60000

    - stage: test
      name: electron-renderer
      script:
        - npm run test:electron-renderer -- $RUN_SINCE -- -- --bail --timeout 60000

    - stage: test
      name: interop - node
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t node --bail

    - stage: test
      name: interop - browser
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t browser --bail

    - stage: test
      name: interop - electron-main
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t electron-main -f ./test/node.js --bail --timeout 60000

    - stage: test
      name: interop - electron-renderer
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t electron-renderer -f ./test/browser.js -bail --timeout 60000

    - stage: test
      name: js-ipfs interface tests - node
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: js-ipfs interface tests - chrome
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: js-ipfs interface tests - chrome webworker
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: js-ipfs interface tests - firefox
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t browser -- --browser firefox

    - stage: test
      name: js-ipfs interface tests - firefox webworker
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000 -- --browser firefox

    - stage: test
      name: js-ipfs interface tests - electron main
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t electron-main --timeout 60000

    - stage: test
      name: js-ipfs interface tests - electron renderer
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t electron-renderer --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - node
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: js-ipfs interface tests - ipfs-client - chrome
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: js-ipfs interface tests - ipfs-client - chrome webworker
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - firefox
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t browser -- --browser firefox

    - stage: test
      name: js-ipfs interface tests - ipfs-client - firefox webworker
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000 -- --browser firefox

    - stage: test
      name: js-ipfs interface tests - ipfs-client - electron main
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t electron-main --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - electron renderer
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t electron-renderer --timeout 60000

    - stage: test
      name: http-api-client interface tests vs go-ipfs - node
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: http-api-client interface tests vs go-ipfs - chrome
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: http-api-client interface tests vs go-ipfs - chrome webworker
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: http-api-client interface tests vs go-ipfs - firefox
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t browser -- --browser firefox

    - stage: test
      name: http-api-client interface tests vs go-ipfs - firefox webworker
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000 -- --browser firefox

    - stage: test
      name: http-api-client interface tests vs js-ipfs - node
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: http-api-client interface tests vs js-ipfs - chrome
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: http-api-client interface tests vs js-ipfs - chrome webworker
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: http-api-client interface tests vs js-ipfs - firefox
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t browser --browser firefox

    - stage: test
      name: http-api-client interface tests vs js-ipfs - firefox webworker
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000 -- --browser firefox

    - stage: test
      name: http-api-client interface tests vs js-ipfs - electron main
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t electron-main --timeout 60000

    - stage: test
      name: http-api-client interface tests vs js-ipfs - electron renderer
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t electron-renderer --timeout 60000

    - stage: test
      name: ipfs-message-port-client interface tests - chrome
      script:
        - npm run test:interface:message-port-client -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: ipfs-message-port-client interface tests - firefox
      script:
        - npm run test:interface:message-port-client -- $RUN_SINCE -- -- --bail -t browser -- --browser firefox

    - stage: test
      name: examples
      script:
        # Travis lets scripts continue even if previous steps fail so need to use &&: https://github.com/travis-ci/travis-ci/issues/1066
        - npm run configure-examples &&
          npm run test -- --scope=example* --concurrency=1

    - stage: release-rc
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release rc
      script:
        # travis does not fetch the whole repo history, but we need that to work out the
        # ref count to publish canary releases properly
        - git fetch --unshallow
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # only run if the last commit was not part of a release
        - if [[ ! `git log -n 1 -q` =~ publish ]]; then npm run release:rc ; fi

    - stage: release-docker
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release docker
      script:
        # travis does not fetch the whole repo history, but we need that to work out the
        # ref count to publish canary releases properly
        - git fetch --unshallow
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # only run if the last commit was not part of a release
        - if [[ ! `git log -n 1 -q` =~ publish ]]; then npm run docker:rc ; fi

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-webui
      script:
        - E2E_IPFSD_TYPE=js npm run test:external -- -- -- https://github.com/ipfs-shipyard/ipfs-webui.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-companion
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/ipfs-companion.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - npm-on-ipfs
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/npm-on-ipfs.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - peer-base
      script:
        - npm run test:external -- -- -- https://github.com/achingbrain/peer-base.git --branch upgrade-to-latest-ipfs-rc --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - service-worker-gateway
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/service-worker-gateway.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - orbit-db
      script:
        - npm run test:external -- -- -- https://github.com/orbitdb/orbit-db.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-log
      script:
        - npm run test:external -- -- -- https://github.com/orbitdb/ipfs-log.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - sidetree
      script:
        - npm run test:external -- -- -- https://github.com/decentralized-identity/sidetree.git --deps=ipfs@next

notifications:
  email: false
