language: node_js

# TODO: enable when windows is faster on travis, currently causes "No output has been received in the last 10m0s"
# cache: npm
cache: false

stages:
  - check
  - test
  - cov

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir dep-check -- -i wrtc -i electron-webrtc
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npx aegir test -t browser
        - npx aegir test -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npx aegir test -t browser -- --browsers FirefoxHeadless
        - npx aegir test -t webworker -- --browsers FirefoxHeadless

    - stage: test
      name: electron
      addons:
        chrome: stable
      script:
        - npx aegir test -t electron-main
        - npx aegir test -t electron-renderer

notifications:
  email: false
