language: node_js
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - 10

os:
  - linux
  - osx
  - windows

script: npx nyc -s npm run test:node -- --bail

jobs:
  include:
    - stage: check
      node_js: 10
      script:
        - npm run lint
        - npm run dep-check
    - stage: test
      name: chrome
      node_js: 10
      addons:
        chrome: stable
      script:
        - npx aegir test -t browser -- --browsers ChromeDocker
        - npx aegir test -t webworker -- --browsers ChromeDocker
    - stage: test
      name: firefox
      node_js: 10
      addons:
        firefox: latest
      script:
        - npx aegir test -t browser -- --browsers FirefoxHeadlessNoCors
        - npx aegir test -t webworker -- --browsers FirefoxHeadlessNoCors
