language: node_js

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - check
  - test
  - release-rc
  - test-external

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4
      # Ensure chrome is the latest version
      # https://stackoverflow.com/questions/57903415/travis-ci-chrome-62-instead-of-77
      - dpkg
  chrome: stable

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi

script: npx nyc -s npm run test:node -- --concurrency 1 -- -- --timeout 10000 --bail
after_success:
  - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  allow_failures:
    - name: external - ipfs-companion
    - name: external - npm-on-ipfs
    - name: external - peer-base
    - name: external - service-worker-gateway
    - name: external - orbit-db
    - name: external - ipfs-log
    - name: external - sidetree
    - name: external - webui
  include:
    - stage: check
      script:
        - npm run build -- --concurrency 1 -- -- --bundlesize
        - npm run dep-check -- --concurrency 1 -- -- -- -i wrtc -i electron-webrtc
        - npm run lint -- --concurrency 1

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npm run test:browser -- --concurrency 1 -- -- --bail

    - stage: test
      name: chrome webworker
      addons:
        chrome: stable
      script:
        - npm run test:webworker -- --concurrency 1 -- -- --bail

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npm run test:browser -- --concurrency 1 -- -- --bail --browsers FirefoxHeadless

    - stage: test
      name: firefox webworker
      addons:
        firefox: latest
      script:
        - npm run test:webworker -- --concurrency 1 -- -- --bail --browsers FirefoxHeadless

    - stage: test
      name: electron-main
      os: osx
      script:
        - npm run test:electron-main -- --concurrency 1 -- -- --bail

    - stage: test
      name: electron-renderer
      os: osx
      script:
        - npm run test:electron-renderer -- --concurrency 1 -- -- --bail

    - stage: test
      name: interop - node
      script:
        - npm run test:interop:node -- --concurrency 1 -- -- --bail

    - stage: test
      name: interop - browser
      script:
        - npm run test:interop:browser -- --concurrency 1 -- -- --bail

    - stage: test
      name: interop - electron-main
      os: osx
      script:
        - npm run test:interop:electron-main -- --concurrency 1 -- -- --bail --timeout 10000

    - stage: test
      name: interop - electron-renderer
      os: osx
      script:
        - npm run test:interop:electron-renderer -- --concurrency 1 -- -- --bail --timeout 10000

    - stage: test
      name: example - browser-add-readable-stream
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-add-readable-stream

    - stage: test
      name: example - browser-browserify
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-browserify

    - stage: test
      name: example - browser-create-react-app
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-create-react-app

    - stage: test
      name: example - browser-mfs
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-mfs

    - stage: test
      name: example - browser-parceljs
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-parceljs

    - stage: test
      name: example - browser-readablestream
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-readablestream

    - stage: test
      name: example - browser-script-tag
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-script-tag

    - stage: test
      name: example - browser-video-streaming
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-video-streaming

    - stage: test
      name: example - browser-vue
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-vue

    - stage: test
      name: example - browser-webpack
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-webpack

    - stage: test
      name: example - circuit-relaying
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- circuit-relaying

    - stage: test
      name: example - custom-ipfs-repo
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- custom-ipfs-repo

    - stage: test
      name: example - custom-libp2p
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- custom-libp2p

    - stage: test
      name: example - exchange-files-in-browser
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- exchange-files-in-browser

    - stage: test
      name: example - explore-ethereum-blockchain
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- explore-ethereum-blockchain

    - stage: test
      name: example - ipfs-101
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- ipfs-101

    - stage: test
      name: example - running-multiple-nodes
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- running-multiple-nodes

    - stage: test
      name: example - traverse-ipld-graphs
      script:
        - cd packages/ipfs
        - npm run build
        - cd examples
        - npm install
        - npm run test -- traverse-ipld-graphs

    - stage: release-rc
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release rc
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm run release:rc -- --yes

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-webui
      script:
        - E2E_IPFSD_TYPE=js npm run test:external -- https://github.com/ipfs-shipyard/ipfs-webui.git --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-companion
      script:
        - npm run test:external -- https://github.com/ipfs-shipyard/ipfs-companion.git --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - npm-on-ipfs
      script:
        - npm run test:external -- https://github.com/ipfs-shipyard/npm-on-ipfs.git --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - peer-base
      script:
        - npm run test:external -- https://github.com/achingbrain/peer-base.git --branch upgrade-to-latest-ipfs-rc --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - service-worker-gateway
      script:
        - npm run test:external -- https://github.com/ipfs-shipyard/service-worker-gateway.git --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - orbit-db
      script:
        - npm run test:external -- https://github.com/orbitdb/orbit-db.git --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-log
      script:
        - npm run test:external -- https://github.com/orbitdb/ipfs-log.git --deps=ipfs@next"

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - sidetree
      script:
        - npm run test:external -- https://github.com/decentralized-identity/sidetree.git --deps=ipfs@next"

notifications:
  email: false
