language: node_js

services:
  - xvfb

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - check
  - test
  - release-rc
  - test-external

node_js:
  - 'lts/*'
  # blocked by https://github.com/hapijs/hapi/issues/4149
  # - 'node'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4
      # Ensure chrome is the latest version
      # https://stackoverflow.com/questions/57903415/travis-ci-chrome-62-instead-of-77
      - dpkg
  chrome: stable

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi
  # only run jobs in packages that have changed since master in PR builds
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export RUN_SINCE='--since master' ; fi

script: npm run test:node -- $RUN_SINCE -- -- --timeout 10000 --bail

jobs:
  allow_failures:
    - name: external - ipfs-webui
    - name: external - ipfs-companion
    - name: external - npm-on-ipfs
    - name: external - peer-base
    - name: external - service-worker-gateway
    - name: external - orbit-db
    - name: external - ipfs-log
    - name: external - sidetree
  include:
    - stage: check
      script:
        - npm run build -- $RUN_SINCE --scope={ipfs,ipfs-http-client,ipfs-message-port-*}
        - npm run dep-check -- $RUN_SINCE -- -- -- -i electron-webrtc
        - npm run lint -- $RUN_SINCE --concurrency 1

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail

    - stage: test
      name: chrome webworker
      addons:
        chrome: stable
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail --browsers FirefoxHeadless

    - stage: test
      name: firefox webworker
      addons:
        firefox: latest
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail --browsers FirefoxHeadless

    - stage: test
      name: electron-main
      os: osx
      script:
        - npm run test:electron-main -- $RUN_SINCE -- -- --bail

    - stage: test
      name: electron-renderer
      os: osx
      script:
        - npm run test:electron-renderer -- $RUN_SINCE -- -- --bail

    - stage: test
      name: interop - node
      script:
        - npm run test:interop:node -- $RUN_SINCE -- -- --bail

    - stage: test
      name: interop - browser
      script:
        - npm run test:interop:browser -- $RUN_SINCE -- -- --bail

    - stage: test
      name: interop - electron-main
      os: osx
      script:
        - npm run test:interop:electron-main -- $RUN_SINCE -- -- --bail --timeout 10000

    - stage: test
      name: interop - electron-renderer
      os: osx
      script:
        - npm run test:interop:electron-renderer -- $RUN_SINCE -- -- --bail --timeout 10000

    - stage: test
      name: examples
      script:
        - npx json -I -f ./lerna.json -e "this.packages.push('examples/*')"
        - npx json -I -f ./lerna.json -e "this.command.bootstrap.nohoist = ['ipfs-css', 'tachyons']"
        - npm run reset
        - npm install
        - npm run build -- --scope={ipfs,ipfs-http-client,ipfs-message-port-*}
        - npm run test -- --scope=example* --concurrency=1

    - stage: release-rc
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release rc
      script:
        # travis does not fetch the whole repo history, but we need that to work out the
        # ref count to publish canary releases properly
        - git fetch --unshallow
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # only run if the last commit was not part of a release
        - if [[ ! `git log -n 1 -q` =~ publish ]]; then npm run release:rc ; fi

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-webui
      script:
        - E2E_IPFSD_TYPE=js npm run test:external -- -- -- https://github.com/ipfs-shipyard/ipfs-webui.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-companion
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/ipfs-companion.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - npm-on-ipfs
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/npm-on-ipfs.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - peer-base
      script:
        - npm run test:external -- -- -- https://github.com/achingbrain/peer-base.git --branch upgrade-to-latest-ipfs-rc --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - service-worker-gateway
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/service-worker-gateway.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - orbit-db
      script:
        - npm run test:external -- -- -- https://github.com/orbitdb/orbit-db.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-log
      script:
        - npm run test:external -- -- -- https://github.com/orbitdb/ipfs-log.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - sidetree
      script:
        - npm run test:external -- -- -- https://github.com/decentralized-identity/sidetree.git --deps=ipfs@next

notifications:
  email: false
