language: node_js

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - check
  - test
  - tag

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4
      # Ensure chrome is the latest version
      # https://stackoverflow.com/questions/57903415/travis-ci-chrome-62-instead-of-77
      - dpkg
  chrome: stable

script: DEBUG=ipfs* npx nyc -s npx aegir test -t node --timeout 10000 --bail
after_success:
  - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir build --bundlesize
        - npx aegir dep-check -- -i wrtc -i electron-webrtc
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npx aegir test -t browser -t webworker -- --browsers FirefoxHeadless

    - stage: test
      name: electron-main
      os: osx
      script:
        - npx aegir test -t electron-main --bail --timeout 10000

    - stage: test
      name: electron-renderer
      os: osx
      script:
        - npx aegir test -t electron-renderer --bail --timeout 10000

    - stage: test
      name: interop - node
      script:
        - mkdir -p node_modules/ipfs-interop/node_modules
        - ln -s `pwd` node_modules/ipfs-interop/node_modules/ipfs
        - export IPFS_JS_EXEC=`pwd`/src/cli/bin.js
        - export IPFS_REUSEPORT=false
        - cd node_modules/ipfs-interop
        - npx aegir test -t node --bail

    - stage: test
      name: interop - browser
      script:
        - mkdir -p node_modules/ipfs-interop/node_modules
        - ln -s `pwd` node_modules/ipfs-interop/node_modules/ipfs
        - export IPFS_JS_EXEC=`pwd`/src/cli/bin.js
        - export IPFS_REUSEPORT=false
        - cd node_modules/ipfs-interop
        - npx aegir test -t browser --bail

    - stage: test
      name: interop - electron-main
      os: osx
      script:
        - mkdir -p node_modules/ipfs-interop/node_modules
        - ln -s `pwd` node_modules/ipfs-interop/node_modules/ipfs
        - export IPFS_JS_EXEC=`pwd`/src/cli/bin.js
        - export IPFS_REUSEPORT=false
        - cd node_modules/ipfs-interop
        - npx aegir test -t electron-main -f ./test/node.js --bail --timeout 10000

    - stage: test
      name: interop - electron-renderer
      os: osx
      script:
        - mkdir -p node_modules/ipfs-interop/node_modules
        - ln -s `pwd` node_modules/ipfs-interop/node_modules/ipfs
        - export IPFS_JS_EXEC=`pwd`/src/cli/bin.js
        - export IPFS_REUSEPORT=false
        - cd node_modules/ipfs-interop
        - npx aegir test -t electron-renderer -f ./test/browser.js --bail --timeout 10000

    - stage: test
      name: external - ipfs-companion
      script:
        - npm run test:external -- ipfs-companion https://github.com/ipfs-shipyard/ipfs-companion.git

    - stage: test
      name: external - npm-on-ipfs
      script:
        - npm run test:external -- npm-on-ipfs https://github.com/ipfs-shipyard/npm-on-ipfs.git

    - stage: test
      name: external - ipfs-pubsub-room
      script:
        - npm run test:external -- ipfs-pubsub-room https://github.com/ipfs-shipyard/ipfs-pubsub-room.git

    - stage: test
      name: external - peer-base
      script:
        - npm run test:external -- peer-base https://github.com/achingbrain/peer-base.git --branch upgrade-to-latest-ipfs-rc

    - stage: test
      name: external - service-worker-gateway
      script:
        - npm run test:external -- service-worker-gateway https://github.com/ipfs-shipyard/service-worker-gateway.git

    - stage: test
      name: external - orbit-db
      script:
        - npm run test:external -- orbit-db https://github.com/orbitdb/orbit-db.git

    - stage: test
      name: external - ipfs-log
      script:
        - npm run test:external -- ipfs-log https://github.com/orbitdb/ipfs-log.git

    - stage: test
      name: external - sidetree
      script:
        - npm run test:external -- sidetree https://github.com/decentralized-identity/sidetree.git

    - stage: test
      name: example - browser-add-readable-stream
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-add-readable-stream

    - stage: test
      name: example - browser-browserify
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-browserify

    - stage: test
      name: example - browser-create-react-app
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-create-react-app

    - stage: test
      name: example - browser-mfs
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-mfs

    - stage: test
      name: example - browser-parceljs
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-parceljs

    - stage: test
      name: example - browser-readablestream
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-readablestream

    - stage: test
      name: example - browser-script-tag
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-script-tag

    - stage: test
      name: example - browser-video-streaming
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-video-streaming

    - stage: test
      name: example - browser-vue
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-vue

    - stage: test
      name: example - browser-webpack
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- browser-webpack

    - stage: test
      name: example - circuit-relaying
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- circuit-relaying

    - stage: test
      name: example - custom-ipfs-repo
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- custom-ipfs-repo

    - stage: test
      name: example - custom-libp2p
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- custom-libp2p

    - stage: test
      name: example - exchange-files-in-browser
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- exchange-files-in-browser

    - stage: test
      name: example - explore-ethereum-blockchain
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- explore-ethereum-blockchain

    - stage: test
      name: example - ipfs-101
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- ipfs-101

    - stage: test
      name: example - running-multiple-nodes
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- running-multiple-nodes

    - stage: test
      name: example - traverse-ipld-graphs
      script:
        - npm run build
        - cd examples
        - npm install
        - npm run test -- traverse-ipld-graphs

    - stage: tag
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: update-last-successful-build
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git remote set-url origin https://$TRAVIS_GITHUB_USER:$TRAVIS_GITHUB_TOKEN@github.com/ipfs/js-ipfs.git
        - npx aegir update-last-successful-build

notifications:
  email: false
