on:
  pull_request:
    branches:
      - '*'

name: Typecheck
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - packages/ipfs
          - packages/ipfs-cli
          - packages/ipfs-client
          - packages/ipfs-core
          - packages/ipfs-core-types
          - packages/ipfs-core-utils
          - packages/ipfs-daemon
          - packages/ipfs-grpc-client
          - packages/ipfs-grpc-server
          - packages/ipfs-http-client
          - packages/ipfs-http-gateway
          - packages/ipfs-http-server
          - packages/ipfs-message-port-client
          - packages/ipfs-message-port-protocol
          - packages/ipfs-message-port-server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: node --version
      - run: npm --version
      - name: Install dependencies
        run: npm install -g @mapbox/node-pre-gyp && npm install
      - name: Typecheck ${{ matrix.project }}
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: ${{ matrix.project }}
